version: '3.8'

services:
  flask-app:
    build: ./flask-microservice
    container_name: flask-app
    ports:
      - "5000:5000"

  node-app:
    build: ./node-docker-app
    container_name: node-app
    ports:
      - "3000:3000"